Refactor
moise10r/school-library pull request #5
Opened 2021-10-12 15:47 UTC by AkashaRojee

Hello!

We refactored the project.

- `main.rb` now only launches app, shows menu and handles user input.
- `app.rb` then processes the menu option selected by user.

Please, review the project.

Thanks!

2021-10-12 16:36 UTC, AshakaE requested changes
### Hi @AkashaRojee & @moise10r  🙋‍♀️, 

Good job so far! 👌
Pull request 👌 
Git flow ✔️ 
Readme  👍 
Your abstraction with the `app.rb` is great but it needs more work 💡 

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-12 16:36 UTC, AshakaE commented on app.rb
> +    person_type = gets.chomp while person_type != '2' && person_type != '1'
All requests for input and input validation should be placed in the `main.rb` file

- [ ] Kindly refactor code

2021-10-12 16:36 UTC, AshakaE commented on app.rb
> +  end
Try to follow the [best practices and solid]( https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) 

- [ ] Kindly refactor code

2021-10-12 16:36 UTC, AshakaE commented on app.rb
> +  end
Try to follow the [best practices and solid]( https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid) 

- [ ] Kindly refactor code

2021-10-13 21:40 UTC, SpaYco approved these changes
Hello 👋,

_This is an additional review as a result of the second opinion request._

I'm sorry this took longer than it should, it totally passed by and got lost in the queue,

You're right, the reasons sent by the CR is for 1.0 projects, so you're good to go here

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2021-10-14 21:59 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🎉✔**
Hello @AkashaRojee 👋🏽
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 22:29 UTC, merged